<a href="https://colab.research.google.com/github/somenath203/BMI-Calculator/blob/main/basic_neural_network_tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# loading packages

import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.6.0'

In [ ]:
# loading the dataset

dataset = pd.read_excel("Folds5x2_pp.xlsx")

X = dataset.iloc[:, :-1].values 
y = dataset.iloc[:, -1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [ ]:
# splitting the data into training set and testing set

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [ ]:
# initialzing the artificial neural network

ann = tf.keras.models.Sequential()

In [ ]:
# adding the input layer and the first hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
# adding the second hiddden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
# adding the output layer

ann.add(tf.keras.layers.Dense(units=1))

In [ ]:
# compiling the artificial neural network

ann.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
# training the artificial neural network model on the training set

ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 105168.3984
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 792.0847
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 196.5844
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 194.5566
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 192.2921
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 189.7090
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 186.3763
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 182.8030
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 178.9122
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 174.2837
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 169.6339
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - l

In [ ]:
# predicting the result of the test set

y_pred = ann.predict(X_test)

np.set_printoptions(precision=2)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[432.51 431.23]
 [463.61 460.01]
 [467.13 461.14]
 ...
 [474.34 473.26]
 [441.12 438.  ]
 [460.33 463.28]]
